from enum import Enum


class MongoCollectionName(str, Enum):
    TRAFFIC_SOURCES = "TRAFFIC_SOURCE_BBIP"
    IP_SOURCES = "IP_SOURCE_BBIP"
    TRAFFIC_DAILY_SUMMARY = "TRAFFIC_DAILY_SUMMARY_BBIP"
    IP_DAILY_SUMMARY = "IP_DAILY_SUMMARY_BBIP"


class SuffixCollectionName(str, Enum):
    TRAFFIC_HISTORIES = "TRAFFIC_HISTORY_BBIP"
    IP_HISTORIES = "IP_HISTORY_BBIP"
