from enum import Enum


class MongoCollectionName(str, Enum):
    BBIP_SOURCES = "BBIP_SOURCES"
    BORDE = "BORDE_BBIP_HISTORY"
    BRAS = "BRAS_BBIP_HISTORY"
    CACHING = "CACHING_BBIP_HISTORY"
    RAI = "RAI_BBIP_HISTORY"
    IXP = "IXP_BBIP_HISTORY"
    DINT = "DINT_BBIP_HISTORY"
    DIST = "DIST_BBIP_HISTORY"
    BBIP_DAILY_SUMMARY = "BBIP_DAILY_SUMMARY"
    IP_SOURCES = "IP_SOURCES"
    IP_BRAS = "IP_BRAS_BBIP_HISTORY"
    IP_DAILY_SUMMARY = "IP_DAILY_SUMMARY"
